CTFd/forms/config.py
from wtforms import BooleanField, SelectField, StringField, TextAreaField
from wtforms.fields.html5 import IntegerField, URLField
from wtforms.widgets.html5 import NumberInput

from CTFd.forms import BaseForm
from CTFd.forms.fields import SubmitField
from CTFd.models import db


class ResetInstanceForm(BaseForm):
    accounts = BooleanField(
        "Accounts",
        description="Deletes all user and team accounts and their associated information",
    )
    submissions = BooleanField(
        "Submissions",
        description="Deletes all records that accounts gained points or took an action",
    )
    challenges = BooleanField(
        "Challenges", description="Deletes all challenges and associated data"
    )
    pages = BooleanField(
        "Pages", description="Deletes all pages and their associated files"
    )
    notifications = BooleanField(
        "Notifications", description="Deletes all notifications"
    )
    submit = SubmitField("Reset CTF")


class AccountSettingsForm(BaseForm):
    domain_whitelist = StringField(
        "Account Email Whitelist",
        description="Comma-seperated email domains which users can register under (e.g. ctfd.io, gmail.com, yahoo.com)",
    )
    team_creation = SelectField(
        "Team Creation",
        description="Control whether users can create their own teams (Teams mode only)",
        choices=[("true", "Enabled"), ("false", "Disabled")],
        default="true",
    )
    team_size = IntegerField(
        widget=NumberInput(min=0),
        description="Amount of users per team (Teams mode only)",
    )
    verify_emails = SelectField(
        "Verify Emails",
        description="Control whether users must confirm their email addresses before playing",
        choices=[("true", "Enabled"), ("false", "Disabled")],
        default="false",
    )
    team_disbanding = SelectField(
        "Team Disbanding",
        description="Control whether team capatins are allowed to disband their own teams",
        choices=[
            ("inactive_only", "Enabled for Inactive Teams"),
            ("disabled", "Disabled"),
        ],
        default="inactive_only",
    )
    name_changes = SelectField(
        "Name Changes",
        description="Control whether users and teams can change their names",
        choices=[("true", "Enabled"), ("false", "Disabled")],
        default="true",
    )

    submit = SubmitField("Update")


class ExportCSVForm(BaseForm):
    table = SelectField(
        "Database Table",
        choices=list(
            zip(sorted(db.metadata.tables.keys()), sorted(db.metadata.tables.keys()))
        ),
    )
    submit = SubmitField("Download CSV")


class LegalSettingsForm(BaseForm):
    tos_url = URLField(
        "Terms of Service URL",
        description="External URL to a Terms of Service document hosted elsewhere",
    )
    tos_text = TextAreaField(
        "Terms of Service", description="Text shown on the Terms of Service page",
    )
    privacy_url = URLField(
        "Privacy Policy URL",
        description="External URL to a Privacy Policy document hosted elsewhere",
    )
    privacy_text = TextAreaField(
        "Privacy Policy", description="Text shown on the Privacy Policy page",
    )
    submit = SubmitField("Update")

CTFd/forms/email.py
from wtforms import TextAreaField
from wtforms.validators import InputRequired

from CTFd.forms import BaseForm
from CTFd.forms.fields import SubmitField


class SendEmailForm(BaseForm):
    text = TextAreaField("Message", validators=[InputRequired()])
    submit = SubmitField("Send")

CTFd/forms/fields.py
from wtforms import SubmitField as _SubmitField


class SubmitField(_SubmitField):
    """
    This custom SubmitField exists because wtforms is dumb.

    See https://github.com/wtforms/wtforms/issues/205, https://github.com/wtforms/wtforms/issues/36
    The .submit() handler in JS will break if the form has an input with the name or id of "submit" so submit fields need to be changed.
    """

    def __init__(self, *args, **kwargs):
        name = kwargs.pop("name", "_submit")
        super().__init__(*args, **kwargs)
        if self.name == "submit" or name:
            self.id = name
            self.name = name

CTFd/admin/__init__.py
import csv
import datetime
import os
from io import BytesIO, StringIO

from flask import Blueprint, abort
from flask import current_app as app
from flask import (
    redirect,
    render_template,
    render_template_string,
    request,
    send_file,
    url_for,
)

admin = Blueprint("admin", __name__)

# isort:imports-firstparty
from CTFd.admin import challenges  # noqa: F401
from CTFd.admin import notifications  # noqa: F401
from CTFd.admin import pages  # noqa: F401
from CTFd.admin import scoreboard  # noqa: F401
from CTFd.admin import statistics  # noqa: F401
from CTFd.admin import submissions  # noqa: F401
from CTFd.admin import teams  # noqa: F401
from CTFd.admin import users  # noqa: F401
from CTFd.cache import cache, clear_config, clear_pages, clear_standings
from CTFd.models import (
    Awards,
    Challenges,
    Configs,
    Notifications,
    Pages,
    Solves,
    Submissions,
    Teams,
    Tracking,
    Unlocks,
    Users,
    db,
    get_class_by_tablename,
)
from CTFd.utils import config as ctf_config
from CTFd.utils import get_config, set_config
from CTFd.utils.decorators import admins_only
from CTFd.utils.exports import export_ctf as export_ctf_util
from CTFd.utils.exports import import_ctf as import_ctf_util
from CTFd.utils.helpers import get_errors
from CTFd.utils.security.auth import logout_user
from CTFd.utils.uploads import delete_file
from CTFd.utils.user import is_admin


@admin.route("/admin", methods=["GET"])
def view():
    if is_admin():
        return redirect(url_for("admin.statistics"))
    return redirect(url_for("auth.login"))


@admin.route("/admin/plugins/<plugin>", methods=["GET", "POST"])
@admins_only
def plugin(plugin):
    if request.method == "GET":
        plugins_path = os.path.join(app.root_path, "plugins")

        config_html_plugins = [
            name
            for name in os.listdir(plugins_path)
            if os.path.isfile(os.path.join(plugins_path, name, "config.html"))
        ]

        if plugin in config_html_plugins:
            config_html = open(
                os.path.join(app.root_path, "plugins", plugin, "config.html")
            ).read()
            return render_template_string(config_html)
        abort(404)
    elif request.method == "POST":
        for k, v in request.form.items():
            if k == "nonce":
                continue
            set_config(k, v)
        with app.app_context():
            clear_config()
        return "1"


@admin.route("/admin/import", methods=["POST"])
@admins_only
def import_ctf():
    backup = request.files["backup"]
    errors = get_errors()
    try:
        import_ctf_util(backup)
    except Exception as e:
        print(e)
        errors.append(repr(e))

    if errors:
        return errors[0], 500
    else:
        return redirect(url_for("admin.config"))


@admin.route("/admin/export", methods=["GET", "POST"])
@admins_only
def export_ctf():
    backup = export_ctf_util()
    ctf_name = ctf_config.ctf_name()
    day = datetime.datetime.now().strftime("%Y-%m-%d")
    full_name = u"{}.{}.zip".format(ctf_name, day)
    return send_file(
        backup, cache_timeout=-1, as_attachment=True, attachment_filename=full_name
    )


@admin.route("/admin/export/csv")
@admins_only
def export_csv():
    table = request.args.get("table")

    # TODO: It might make sense to limit dumpable tables. Config could potentially leak sensitive information.
    model = get_class_by_tablename(table)
    if model is None:
        abort(404)

    temp = StringIO()
    writer = csv.writer(temp)

    header = [column.name for column in model.__mapper__.columns]
    writer.writerow(header)

    responses = model.query.all()

    for curr in responses:
        writer.writerow(
            [getattr(curr, column.name) for column in model.__mapper__.columns]
        )

    temp.seek(0)

    # In Python 3 send_file requires bytes
    output = BytesIO()
    output.write(temp.getvalue().encode("utf-8"))
    output.seek(0)
    temp.close()

    return send_file(
        output,
        as_attachment=True,
        cache_timeout=-1,
        attachment_filename="{name}-{table}.csv".format(
            name=ctf_config.ctf_name(), table=table
        ),
    )


@admin.route("/admin/config", methods=["GET", "POST"])
@admins_only
def config():
    # Clear the config cache so that we don't get stale values
    clear_config()

    configs = Configs.query.all()
    configs = {c.key: get_config(c.key) for c in configs}

    themes = ctf_config.get_themes()
    themes.remove(get_config("ctf_theme"))

    return render_template("admin/config.html", themes=themes, **configs)


@admin.route("/admin/reset", methods=["GET", "POST"])
@admins_only
def reset():
    if request.method == "POST":
        require_setup = False
        logout = False
        next_url = url_for("admin.statistics")

        data = request.form

        if data.get("pages"):
            _pages = Pages.query.all()
            for p in _pages:
                for f in p.files:
                    delete_file(file_id=f.id)

            Pages.query.delete()

        if data.get("notifications"):
            Notifications.query.delete()

        if data.get("challenges"):
            _challenges = Challenges.query.all()
            for c in _challenges:
                for f in c.files:
                    delete_file(file_id=f.id)
            Challenges.query.delete()

        if data.get("accounts"):
            Users.query.delete()
            Teams.query.delete()
            require_setup = True
            logout = True

        if data.get("submissions"):
            Solves.query.delete()
            Submissions.query.delete()
            Awards.query.delete()
            Unlocks.query.delete()
            Tracking.query.delete()

        if require_setup:
            set_config("setup", False)
            cache.clear()
            logout_user()
            next_url = url_for("views.setup")

        db.session.commit()

        clear_pages()
        clear_standings()
        clear_config()

        if logout is True:
            cache.clear()
            logout_user()

        db.session.close()
        return redirect(next_url)

    return render_template("admin/reset.html")

CTFd/utils/config/__init__.py
import os
import time

from flask import current_app as app

from CTFd.constants.themes import DEFAULT_THEME
from CTFd.utils import get_app_config, get_config
from CTFd.utils.modes import TEAMS_MODE, USERS_MODE


def ctf_name():
    name = get_config("ctf_name")
    return name if name else "CTFd"


def user_mode():
    return get_config("user_mode")


def is_users_mode():
    return user_mode() == USERS_MODE


def is_teams_mode():
    return user_mode() == TEAMS_MODE


def ctf_logo():
    return get_config("ctf_logo")


def ctf_theme():
    theme = get_config("ctf_theme")
    return theme if theme else ""


def ctf_theme_candidates():
    yield ctf_theme()
    if bool(get_app_config("THEME_FALLBACK")):
        yield DEFAULT_THEME


def is_setup():
    return bool(get_config("setup")) is True


def is_scoreboard_frozen():
    freeze = get_config("freeze")

    if freeze:
        freeze = int(freeze)
        if freeze < time.time():
            return True

    return False


def can_send_mail():
    return mailserver() or mailgun()


def get_mail_provider():
    if get_config("mail_server") and get_config("mail_port"):
        return "smtp"
    if get_config("mailgun_api_key") and get_config("mailgun_base_url"):
        return "mailgun"
    if app.config.get("MAIL_SERVER") and app.config.get("MAIL_PORT"):
        return "smtp"
    if app.config.get("MAILGUN_API_KEY") and app.config.get("MAILGUN_BASE_URL"):
        return "mailgun"


def mailgun():
    if app.config.get("MAILGUN_API_KEY") and app.config.get("MAILGUN_BASE_URL"):
        return True
    if get_config("mailgun_api_key") and get_config("mailgun_base_url"):
        return True
    return False


def mailserver():
    if app.config.get("MAIL_SERVER") and app.config.get("MAIL_PORT"):
        return True
    if get_config("mail_server") and get_config("mail_port"):
        return True
    return False


def get_themes():
    dir = os.path.join(app.root_path, "themes")
    return [
        name
        for name in os.listdir(dir)
        if os.path.isdir(os.path.join(dir, name)) and name != "admin"
    ]

CTFd/themes/admin/templates/configs/accounts.html
<div role="tabpanel" class="tab-pane config-section" id="accounts">

	{% set verify_emails = "true" if verify_emails == True else "false" %}
	{% set name_changes = "true" if name_changes == True else "false" %}
	{% set team_creation = "false" if team_creation == False else "true" %}
	{% with form = Forms.config.AccountSettingsForm(verify_emails=verify_emails, name_changes=name_changes, team_disbanding=team_disbanding, team_creation=team_creation) %}
	<form method="POST" autocomplete="off" class="w-100">

		<div class="form-group">
			{{ form.domain_whitelist.label }}
			{{ form.domain_whitelist(class="form-control", value=domain_whitelist or "") }}
			<small class="form-text text-muted">
				{{ form.domain_whitelist.description }}
			</small>
		</div>

		<div class="form-group">
			{{ form.verify_emails.label }}
			{{ form.verify_emails(class="form-control custom-select") }}
			<small class="form-text text-muted">
				{{ form.verify_emails.description }}
			</small>
		</div>

		<div class="form-group">
			{{ form.team_creation.label }}
			{{ form.team_creation(class="form-control", value=team_creation) }}
			<small class="form-text text-muted">
				{{ form.team_creation.description }}
			</small>
		</div>

		<div class="form-group">
			{{ form.team_size.label }}
			{{ form.team_size(class="form-control", value=team_size) }}
			<small class="form-text text-muted">
				{{ form.team_size.description }}
			</small>
		</div>

		<div class="form-group">
			{{ form.team_disbanding.label }}
			{{ form.team_disbanding(class="form-control", value=team_disbanding) }}
			<small class="form-text text-muted">
				{{ form.team_disbanding.description }}
			</small>
		</div>

		<div class="form-group">
			{{ form.name_changes.label }}
			{{ form.name_changes(class="form-control custom-select") }}
			<small class="form-text text-muted">
				{{ form.name_changes.description }}
			</small>
		</div>

		{{ form.submit(class="btn btn-md btn-primary float-right") }}
	</form>
	{% endwith %}
</div>

CTFd/themes/admin/templates/configs/appearance.html
<div role="tabpanel" class="tab-pane config-section active" id="appearance">
	<form method="POST" autocomplete="off" class="w-100">
		<div class="form-group">
			<label for="ctf_name">
				Competition Name
				<small class="form-text text-muted">Competition name displayed instead of a logo</small>
			</label>
			<input class="form-control" id='ctf_name' name='ctf_name' type='text' placeholder="CTF Name"
				   {% if ctf_name is defined and ctf_name != None %}value="{{ ctf_name }}"{% endif %}>
		</div>

		<div class="form-group">
			<label>
				CTF Description<br>
				<small class="form-text text-muted">
					Description for the CTF
				</small>
			</label>
			<textarea class="form-control" type="text" id="ctf_description" name="ctf_description" rows="5">{{ ctf_description }}</textarea>
		</div>

		<div class="form-group">
			<label for="user_mode">
				User Mode
				<small class="form-text text-muted">User mode allows users to register as themselves
					or choose to form teams.
				</small>
			</label>
			<div data-toggle="tooltip" data-placement="bottom" title="In order to change User Mode you must reset your CTF and delete all accounts">
				<select class="form-control custom-select" id="user_mode" name="user_mode" disabled="true" style="z-index: -1;">
					<option value="teams" {% if user_mode == 'teams' %}selected{% endif %}>
						Teams
					</option>
					<option value="users" {% if user_mode == 'users' %}selected{% endif %}>
						Users
					</option>
				</select>
			</div>
		</div>

		<button type="submit" class="btn btn-md btn-primary float-right">Update</button>
	</form>
</div>

CTFd/themes/admin/templates/configs/backup.html
<div role="tabpanel" class="tab-pane config-section" id="backup">
	<ul class="nav nav-tabs mb-3" role="tablist">
		<li class="nav-item">
			<a class="nav-link active" href="#export-ctf" aria-controls="export-ctf" role="tab"
			   data-toggle="tab">Export</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="#import-ctf" aria-controls="import-ctf" role="tab" data-toggle="tab">Import</a>
		</li>
		<li class="nav-item">
			<a class="nav-link " href="#save-csv" aria-controls="save-csv" role="tab" data-toggle="tab">Download CSV</a>
		</li>
	</ul>
	<div class="tab-content">
		<div role="tabpanel" class="tab-pane active" id="export-ctf">
			<div class="form-group">
				<p>Exports are an archive of your CTF in its current state. They can be re-imported into other CTFd
					instances or used by scripts and third parties to calculate statistics.</p>
				<p>To download an export click the button below.</p>
			</div>
			<div class="form-group">
				<a href="{{ url_for('admin.export_ctf') }}" id="export-button" class="btn btn-warning">Export</a>
			</div>
		</div>
		<div role="tabpanel" class="tab-pane" id="import-ctf">
			<div class="form-group">
				<p>You can import saved CTFd exports by uploading them below. This will completely wipe your existing
					CTFd instance and all your data will be replaced by the imported data.
					You should only import data that you trust!</p>

				<div class="alert alert-warning" role="alert">
					IMPORTING A CTF WILL COMPLETELY WIPE YOUR EXISTING DATA
				</div>
			</div>
			<div class="form-group">
				<label for="container-files">Import File</label>
				<input class="form-control-file" type="file" name="backup" id="import-file" accept=".zip">
			</div>
			<input id="import-button" type="submit" class="btn btn-warning" value="Import">
		</div>
		<div role="tabpanel" class="tab-pane" id="save-csv">
			{% with form = Forms.config.ExportCSVForm() %}
			<form method="GET" action="{{ url_for('admin.export_csv') }}">
				<div class="form-group">
					{{ form.table.label }}
					{{ form.table(class="form-control custom-select") }}
				</div>
				<input type="submit" class="btn btn-warning" value="Download CSV">
			</form>
			{% endwith %}
		</div>
	</div>
</div>

CTFd/themes/admin/templates/configs/email.html
<div role="tabpanel" class="tab-pane config-section" id="email">
	<form method="POST" autocomplete="off" class="w-100">
		<h5>Email Content</h5>
		<small class="form-text text-muted">
			Customize CTFd emails with <a href="https://docs.ctfd.io/docs/settings/emails/#email-content" target="_blank">predefined variables</a> and custom content
		</small>
		<ul class="nav nav-tabs mt-3" role="tablist">
			<li class="nav-item active">
				<a class="nav-link active" href="#confirmation-email-tab" role="tab" data-toggle="tab">
					Confirmation
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#account-details-email-tab" role="tab" data-toggle="tab">Account Details</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#password-reset-email-tab" role="tab" data-toggle="tab">Password Reset</a>
			</li>
		</ul>

		<div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="confirmation-email-tab">
				<div class="form-group">
					<label class="pt-3">
						Account Registration<br>
						<small class="form-text text-muted">
							Email sent to users after they've registered their account entirely
						</small>
					</label>
					<div>
						<label>
							Subject
						</label>
						<input class="form-control" id='successful_registration_email_subject' name='successful_registration_email_subject' type='text'
							value="{{ successful_registration_email_subject or ''}}">
						<label>
							Body
						</label>
						<textarea class="form-control" type="text" id="successful_registration_email_body" name="successful_registration_email_body"
							rows="5">{{ successful_registration_email_body or '' }}</textarea>
					</div>
				</div>

				<div class="form-group">
					<label class="pt-3">
						Account Confirmation<br>
						<small class="form-text text-muted">
							Email sent to users to confirm their account
						</small>
					</label>
					<div>
						<label>
							Subject
						</label>
						<input class="form-control" id='verification_email_subject' name='verification_email_subject' type='text' value="{{ verification_email_subject or ''}}">
						<label>
							Body
						</label>
						<textarea class="form-control" type="text" id="verification_email_body" name="verification_email_body"
							rows="5">{{ verification_email_body or '' }}</textarea>
					</div>
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="account-details-email-tab">
				<div class="form-group">
					<label class="pt-3">
						New Account Details<br>
						<small class="form-text text-muted">
							Email sent to new users (created by an admin) with their initial account details
						</small>
					</label>
					<div>
						<label>
							Subject
						</label>
						<input class="form-control" id='user_creation_email_subject' name='user_creation_email_subject' type='text'
							value="{{ user_creation_email_subject or ''}}">
						<label>
							Body
						</label>
						<textarea class="form-control" type="text" id="user_creation_email_body" name="user_creation_email_body"
							rows="5">{{ user_creation_email_body or '' }}</textarea>
					</div>
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="password-reset-email-tab">
				<div class="form-group">
					<label class="pt-3">
						Password Reset Request<br>
						<small class="form-text text-muted">
							Email sent whent a user requests a password reset
						</small>
					</label>
					<div>
						<label>
							Subject
						</label>
						<input class="form-control" id='password_reset_subject' name='password_reset_subject' type='text'
							value="{{ password_reset_subject or ''}}">
						<label>
							Body
						</label>
						<textarea class="form-control" type="text" id="password_reset_body" name="password_reset_body"
							rows="5">{{ password_reset_body or '' }}</textarea>
					</div>
				</div>

				<div class="form-group">
					<label class="pt-3">
						Password Reset Confirmation<br>
						<small class="form-text text-muted">
							Email sent whent a user successfully resets their password
						</small>
					</label>
					<div>
						<label>
							Subject
						</label>
						<input class="form-control" id='password_change_alert_subject' name='password_change_alert_subject' type='text'
							value="{{ password_change_alert_subject or ''}}">
						<label>
							Body
						</label>
						<textarea class="form-control" type="text" id="password_change_alert_body" name="password_change_alert_body"
							rows="5">{{ password_change_alert_body or '' }}</textarea>
					</div>
				</div>
			</div>
		</div>

		<hr class="my-5">

		<h5>Email Server</h5>
		<small class="form-text text-muted">
			Change the email server used by CTFd to send email
		</small>
		<ul class="nav nav-tabs my-3" role="tablist">
			<li class="nav-item active">
				<a class="nav-link active" href="#mailserver" role="tab" data-toggle="tab">Mail
					Server</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#mailgun" role="tab" data-toggle="tab">Mailgun</a>
			</li>
		</ul>

		<div class="form-group">
			<label>
				Mail From Address<br>
				<small class="form-text text-muted">
					Email address used to send email
				</small>
			</label>
			<input class="form-control" id='mailfrom_addr' name='mailfrom_addr' type='text' {% if mailfrom_addr is defined and mailfrom_addr != None %}value="{{ mailfrom_addr }}"{% endif %}>
		</div>

		<div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="mailserver">

				<div class="form-group">
					<label>
						Mail Server Address<br>
						<small class="form-text text-muted">
							Mail Server Address
						</small>
					</label>
					<input class="form-control" id='mail_server' name='mail_server' type='text'
						   {% if mail_server is defined and mail_server != None %}value="{{ mail_server }}"{% endif %}>
				</div>

				<div class="form-group">
					<label>
						Mail Server Port<br>
						<small class="form-text text-muted">
							Mail Server Port
						</small>
					</label>
					<input class="form-control" id='mail_port' name='mail_port' type='text'
						   {% if mail_port is defined and mail_port != None %}value="{{ mail_port }}"{% endif %}>
				</div>
				<div class="form-check">
					<label>
						<input id="mail_useauth" name="mail_useauth" type="checkbox"
							   {% if mail_useauth %}checked{% endif %}>
						Use Mail Server Username and Password
					</label>
				</div>
				<div id="mail_username_password">
					<div class="form-group">
						<label>
							Username<br>
							<small class="form-text text-muted">
								Mail Server Account Username
							</small>
						</label>
						{% if mail_username is defined and mail_username != None %}
							<label>
								<sup class="form-text text-muted">A mail server username is currently set</sup>
							</label>
						{% endif %}
						<input class="form-control" id='mail_username' name='mail_username' autocomplete='off' type='text'>
					</div>
					<div class="form-group">
						<label for="mail_password">
							Password<br>
							<small class="form-text text-muted">
								Mail Server Account Password
							</small>
						</label>
						{% if mail_password is defined and mail_password != None %}
							<label>
								<sup class="form-text text-muted">An mail server password is currently set</sup>
							</label>
						{% endif %}
						<input class="form-control" id='mail_password' name='mail_password' autocomplete='off' type='password'>
					</div>
					<sup>Uncheck setting and update to remove username and password</sup>
					<br>
					<br>
				</div>
				<div class="form-check">
					<label>
						<input id="mail_ssl" name="mail_ssl" type="checkbox" {% if mail_ssl %}checked{% endif %}>
						SSL
					</label>
				</div>
				<div class="form-check">
					<label>
						<input id="mail_tls" name="mail_tls" type="checkbox" {% if mail_tls %}checked{% endif %}>
						TLS
					</label>
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="mailgun">
				<div class="alert alert-warning" role="alert">
					Mailgun integration is deprecated! Please see your Mailgun account for SMTP credentials.
				</div>
				<div class="form-group">
					<label>
						Mailgun API Base URL<br>
						<small class="form-text text-muted">
							Mailgun API Base URL
						</small>
					</label>
					<input class="form-control" id='mailgun_base_url' name='mailgun_base_url' type='text'
						   {% if mailgun_base_url is defined and mailgun_base_url != None %}value="{{ mailgun_base_url }}"{% endif %}>
				</div>
				<div class="form-group">
					<label>
						Mailgun API Key<br>
						<small class="form-text text-muted">
							Mailgun API Key
						</small>
					</label>
					<input class="form-control" id='mailgun_api_key' name='mailgun_api_key' type='text'
						   {% if mailgun_api_key is defined and mailgun_api_key != None %}value="{{ mailgun_api_key }}"{% endif %}>
				</div>
			</div>
		</div>
		<button type="submit" class="btn btn-md btn-primary float-right">Update</button>
	</form>
</div>

CTFd/themes/admin/templates/configs/fields.html
<div role="tabpanel" class="tab-pane config-section" id="fields">
	<form method="POST" autocomplete="off" class="w-100">
		<h5>Custom Fields</h5>

		<small class="form-text text-muted">
			Add custom fields to get additional data from your participants
		</small>

		<ul class="nav nav-tabs mt-3" role="tablist">
			<li class="nav-item active">
				<a class="nav-link active" href="#user-fields" role="tab" data-toggle="tab">
					Users
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#team-fields" role="tab" data-toggle="tab">
					Teams
				</a>
			</li>
		</ul>

		<div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="user-fields">
				<div class="col-md-12 py-3">
					<small>Custom user fields are shown during registration. Users can optionally edit these fields in their profile.</small>
				</div>

				<div id="user-field-list" class="pt-3">
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="team-fields">
				<div class="col-md-12 py-3">
					<small>Custom team fields are shown during team creation. Team captains can optionally edit these fields in the team profile.</small>
				</div>

				<div id="team-field-list" class="pt-3">
				</div>
			</div>
		</div>
	</form>
</div>

CTFd/themes/admin/templates/configs/legal.html
<div role="tabpanel" class="tab-pane config-section" id="legal">

	{% with form = Forms.config.LegalSettingsForm(tos_url=tos_url, tos_text=tos_text, privacy_url=privacy_url, privacy_text=privacy_text) %}
	<form method="POST" autocomplete="off" class="w-100">
		<ul class="nav nav-tabs mb-3">
			<li class="nav-item">
				<a class="nav-link active" href="#tos-config" role="tab" data-toggle="tab">
					Terms of Service
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#privacy-policy-config" role="tab" data-toggle="tab">
					Privacy Policy
				</a>
			</li>
		</ul>

		<div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="tos-config">
				<div class="form-group">
					{{ form.tos_url.label }}
					{{ form.tos_url(class="form-control") }}
					<small class="form-text text-muted">
						{{ form.tos_url.description }}
					</small>
				</div>
				<div class="form-group">
					{{ form.tos_text.label }}
					<small class="form-text text-muted">
						{{ form.tos_text.description }}
					</small>
					{{ form.tos_text(class="form-control markdown", rows=15) }}
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="privacy-policy-config">
				<div class="form-group">
					{{ form.privacy_url.label }}
					{{ form.privacy_url(class="form-control") }}
					<small class="form-text text-muted">
						{{ form.privacy_url.description }}
					</small>
				</div>
				<div class="form-group">
					{{ form.privacy_text.label }}
					<small class="form-text text-muted">
						{{ form.privacy_text.description }}
					</small>
					{{ form.privacy_text(class="form-control markdown", rows=15) }}
				</div>
			</div>
		</div>

		{{ form.submit(class="btn btn-md btn-primary float-right") }}
	</form>
	{% endwith %}
</div>